# Overrides this port configuration so
# the Spark/Zookeeper/Kafka cluster can
# be run standalone.

# NOTE: Spark Master isn't port forwarded because of Akka networking problems.
# See https://issues.apache.org/jira/browse/SPARK-4389

version: "2"
services:
  spark_master:
    ports:
      - "8080:8080" # Web UI

  spark_worker:
    ports:
      - "4040:4040" # Web UI
      - "0:7001"
      - "0:7002"
      - "0:7003"
      - "0:7004"
      - "0:7005"
      - "0:7006"
      - "0:7080"
      - "0:7081"

  zookeeper:
    ports:
      - "2181:2181"

  kafka:
    ports:
      - "9092:9092" # Kafka Protocol
      - "9999:9999" #JMX
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://$HOST_IP:9092

  schema_registry:
    ports:
      - "8081:8081" # REST API

  # UI for investigating Kafka. Not necessary for running integration tests.
  kafka_manager:
    image: bgchops-docker-dockerv2-local.artifactoryonline.com/bgch-dp/kafka-manager:1.2.9.14
    links:
      - kafka
      - zookeeper
    ports:
      - "9000:9000"
    environment:
      - ZK_HOSTS=zookeeper:2181
      # - APPLICATION_SECRET=letmein
